"""A setuptools based setup module.
See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""
# IMPORTANT: this file is autogenerated. Do not edit it manually.
# All changes will be lost after `poetry-setup` command execution.
# ----------------------------------------------------------------
# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from os import path
# io.open is needed for projects that support Python 2.7
# It ensures open() defaults to text mode with universal newlines,
# and accepts an argument to specify the text encoding
# Python 3 only projects can skip this import
from io import open
here = path.abspath(path.dirname(__file__))
# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
# Arguments marked as "Required" below must be included for upload to PyPI.
# Fields marked as "Optional" may be commented out.
setup(
    # https://packaging.python.org/specifications/core-metadata/#name
    name='app',  # Required
    # https://www.python.org/dev/peps/pep-0440/
    # https://packaging.python.org/en/latest/single_source_version.html
    version='0.1.0',  # Required
    # https://packaging.python.org/specifications/core-metadata/#summary
    description="The description of the package",  # Required
    # https://packaging.python.org/specifications/core-metadata/#description-optional
    long_description=long_description,  # Optional
    # https://packaging.python.org/specifications/core-metadata/#description-content-type-optional
    long_description_content_type='text/markdown',  # Optional (see note above)
    url="https://github.com/kevinnguyenai/python-poetry-demo",  # Optional
    author="Kevin Nguyen",  # Optional
    author_email="kevin.nguyen.ai@gmail.com",  # Optional
    # For a list of valid classifiers, see https://pypi.org/classifiers/
        classifiers=[u'License :: OSI Approved :: MIT License',
                     u'Programming Language :: Python :: 2',
                     u'Programming Language :: Python :: 2.7',
                     u'Programming Language :: Python :: 3',
                     u'Programming Language :: Python :: 3.4',
                     u'Programming Language :: Python :: 3.5',
                     u'Programming Language :: Python :: 3.6',
                     u'Programming Language :: Python :: 3.7',
                     u'Topic :: Software Development :: Build Tools',
                     u'Topic :: Software Development :: Libraries :: Python Modules'],  # Optional
        keywords=' '.join([u'packaging', u'python-poetry-demo']),  # Optional
    packages=find_packages(
            ),  # Required
    # https://packaging.python.org/en/latest/requirements.html
    install_requires=[
            'pathlib2 (>=2.2,<3.0); python_version >= "2.7" and python_version < "2.8"',
            'deal (>=0.5)',
            'django (==1.11)',
            'toml (>=0.9,<0.10)',
            'requests[security] (>=2.13,<3.0)',
            ],  # Optional
    # https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi
    dependency_links=[
            'git+https://github.com/sdispater/cleo.git@master#egg=cleo',
            ],  # Optional
    # https://stackoverflow.com/a/16576850
    include_package_data=True,
    entry_points={  # Optional
            'console_scripts': [
                'my-script=app.core:main',
            ],
    },
    # https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
    project_urls={  # Optional
            'homepage': 'https://github.com/kevinnguyenai/python-poetry-demo',
            },
)
